namespace GitCandy.Data;

internal static class SchemaLimits
{
    public const int IdentityKey = 450;
    public const int IdentityStoreKey = 128;
    public const int UserDisplayName = 128;
    public const int UserDescription = 512;
    public const int RepositoryName = 50;
    public const int RepositoryStorageName = 100;
    public const int RepositoryDescription = 500;
    public const int TeamName = 20;
    public const int NamespaceSlug = 50;
    public const int RenameReason = 500;
    public const int TeamDescription = 500;
    public const int SshKeyType = 20;
    public const int SshFingerprint = 47;
    public const int SshPublicKey = 600;
    public const int IssueTitle = 256;
    public const int IssueBody = 65536;
    public const int IssueDetail = 1000;
    public const int IssueLabelName = 50;
    public const int IssueLabelColor = 6;
    public const int IssueLabelDescription = 200;
    public const int IssueMilestoneTitle = 100;
    public const int IssueMilestoneDescription = 2000;
    public const int CommitSha = 64;
    public const int GitRefName = 255;
    public const int PullRequestPairKey = 520;
    public const int GitPath = 1024;
    public const int ReviewAnchorContext = 8192;
    public const int CredentialName = 100;
    public const int Sha256Hash = 64;
    public const int TokenPrefix = 16;
    public const int CredentialScopes = 1000;
    public const int CredentialKind = 32;
    public const int AuditAction = 64;
    public const int AuditOutcome = 32;
    public const int AuditDetail = 1000;
    public const int IntegrationEventId = 64;
    public const int IntegrationEventType = 32;
    public const int IntegrationActorName = 100;
    public const int IntegrationPayload = 32768;
    public const int IntegrationName = 100;
    public const int TargetUrl = 2048;
    public const int ProtectedSecret = 4096;
    public const int WebhookDeliveryId = 32;
    public const int WebhookErrorCode = 64;
    public const int CheckContext = 100;
    public const int CheckDescription = 500;
    public const int CheckExternalId = 128;
}
