// <auto-generated />
using System;
using GitCandy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GitCandy.Data.SqlServer.Migrations
{
    [DbContext(typeof(GitCandyDbContext))]
    [Migration("20260711093819_StableNamespaces")]
    partial class StableNamespaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyLegacyRepositoryRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedProject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedProject")
                        .IsUnique()
                        .HasDatabaseName("IX_LegacyRepositoryRoutes_NormalizedProject");

                    b.HasIndex("RepositoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_LegacyRepositoryRoutes_RepositoryId");

                    b.ToTable("LegacyRepositoryRoutes", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_NormalizedSlug");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_TeamId")
                        .HasFilter("[TeamId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Namespaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAtUtc = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NormalizedSlug = "LEGACY",
                            OwnerType = 0,
                            Slug = "legacy",
                            Version = 0
                        });
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespaceAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_NamespaceAliases_ExpiresAtUtc");

                    b.HasIndex("NamespaceId", "CreatedAtUtc")
                        .HasDatabaseName("IX_NamespaceAliases_NamespaceId_CreatedAtUtc");

                    b.ToTable("NamespaceAliases", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespaceClaim", b =>
                {
                    b.Property<string>("NormalizedSlug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<long?>("NamespaceAliasId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NormalizedSlug");

                    b.HasIndex("NamespaceAliasId")
                        .IsUnique()
                        .HasDatabaseName("IX_NamespaceClaims_NamespaceAliasId")
                        .HasFilter("[NamespaceAliasId] IS NOT NULL");

                    b.HasIndex("NamespaceId")
                        .IsUnique()
                        .HasDatabaseName("IX_NamespaceClaims_NamespaceId")
                        .HasFilter("[NamespaceId] IS NOT NULL");

                    b.ToTable("NamespaceClaims", (string)null);

                    b.HasData(
                        new
                        {
                            NormalizedSlug = "ACCOUNT",
                            ClaimType = 3,
                            Slug = "account"
                        },
                        new
                        {
                            NormalizedSlug = "API",
                            ClaimType = 3,
                            Slug = "api"
                        },
                        new
                        {
                            NormalizedSlug = "ASSETS",
                            ClaimType = 3,
                            Slug = "assets"
                        },
                        new
                        {
                            NormalizedSlug = "GIT",
                            ClaimType = 3,
                            Slug = "git"
                        },
                        new
                        {
                            NormalizedSlug = "HEALTH",
                            ClaimType = 3,
                            Slug = "health"
                        },
                        new
                        {
                            NormalizedSlug = "HOME",
                            ClaimType = 3,
                            Slug = "home"
                        },
                        new
                        {
                            NormalizedSlug = "IDENTITY",
                            ClaimType = 3,
                            Slug = "identity"
                        },
                        new
                        {
                            NormalizedSlug = "LEGACY",
                            ClaimType = 1,
                            NamespaceId = 1L,
                            Slug = "legacy"
                        },
                        new
                        {
                            NormalizedSlug = "REPOSITORY",
                            ClaimType = 3,
                            Slug = "repository"
                        },
                        new
                        {
                            NormalizedSlug = "SETTING",
                            ClaimType = 3,
                            Slug = "setting"
                        },
                        new
                        {
                            NormalizedSlug = "SIGNIN-OIDC",
                            ClaimType = 3,
                            Slug = "signin-oidc"
                        },
                        new
                        {
                            NormalizedSlug = "SIGNOUT-CALLBACK-OIDC",
                            ClaimType = 3,
                            Slug = "signout-callback-oidc"
                        },
                        new
                        {
                            NormalizedSlug = "TEAM",
                            ClaimType = 3,
                            Slug = "team"
                        });
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRenameEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<string>("NewSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectId", "EventType", "OccurredAtUtc")
                        .HasDatabaseName("IX_RenameEvents_Subject_Window");

                    b.ToTable("RenameEvents", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepository", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowAnonymousRead")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAnonymousWrite")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ForkNetworkRoot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForkedFromRepository")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StorageName")
                        .IsUnique()
                        .HasDatabaseName("IX_Repositories_StorageName");

                    b.HasIndex("NamespaceId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Repositories_NamespaceId_NormalizedName");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepositoryAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_RepositoryAliases_ExpiresAtUtc");

                    b.HasIndex("NamespaceId");

                    b.HasIndex("RepositoryId", "CreatedAtUtc")
                        .HasDatabaseName("IX_RepositoryAliases_RepositoryId_CreatedAtUtc");

                    b.ToTable("RepositoryAliases", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepositoryClaim", b =>
                {
                    b.Property<long>("NamespaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedSlug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<long?>("RepositoryAliasId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NamespaceId", "NormalizedSlug");

                    b.HasIndex("RepositoryAliasId")
                        .IsUnique()
                        .HasDatabaseName("IX_RepositoryClaims_RepositoryAliasId")
                        .HasFilter("[RepositoryAliasId] IS NOT NULL");

                    b.HasIndex("RepositoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_RepositoryClaims_RepositoryId")
                        .HasFilter("[RepositoryId] IS NOT NULL");

                    b.ToTable("RepositoryClaims", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandySshKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(47)
                        .HasColumnType("nchar(47)")
                        .IsFixedLength();

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("IX_SshKeys_Fingerprint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SshKeys_UserId");

                    b.ToTable("SshKeys", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_NormalizedName");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyTeamRepositoryRole", b =>
                {
                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AllowRead")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWrite")
                        .HasColumnType("bit");

                    b.HasKey("TeamId", "RepositoryId");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("IX_TeamRepositoryRoles_RepositoryId");

                    b.ToTable("TeamRepositoryRoles", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyUserRepositoryRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AllowRead")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWrite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RepositoryId");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("IX_UserRepositoryRoles_RepositoryId");

                    b.ToTable("UserRepositoryRoles", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyUserTeamRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_UserTeamRoles_TeamId");

                    b.ToTable("UserTeamRoles", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Identity.GitCandyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyLegacyRepositoryRoute", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyRepository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespace", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyTeam", "Team")
                        .WithOne("Namespace")
                        .HasForeignKey("GitCandy.Data.Domain.GitCandyNamespace", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", "User")
                        .WithOne("Namespace")
                        .HasForeignKey("GitCandy.Data.Domain.GitCandyNamespace", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespaceAlias", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespace", "Namespace")
                        .WithMany("Aliases")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespaceClaim", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespaceAlias", "NamespaceAlias")
                        .WithOne()
                        .HasForeignKey("GitCandy.Data.Domain.GitCandyNamespaceClaim", "NamespaceAliasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespace", "Namespace")
                        .WithMany()
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Namespace");

                    b.Navigation("NamespaceAlias");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepository", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespace", "Namespace")
                        .WithMany("Repositories")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepositoryAlias", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespace", "Namespace")
                        .WithMany()
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Domain.GitCandyRepository", "Repository")
                        .WithMany("Aliases")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepositoryClaim", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyNamespace", "Namespace")
                        .WithMany()
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Domain.GitCandyRepositoryAlias", "RepositoryAlias")
                        .WithOne()
                        .HasForeignKey("GitCandy.Data.Domain.GitCandyRepositoryClaim", "RepositoryAliasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GitCandy.Data.Domain.GitCandyRepository", "Repository")
                        .WithOne()
                        .HasForeignKey("GitCandy.Data.Domain.GitCandyRepositoryClaim", "RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Namespace");

                    b.Navigation("Repository");

                    b.Navigation("RepositoryAlias");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandySshKey", b =>
                {
                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", "User")
                        .WithMany("SshKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyTeamRepositoryRole", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyRepository", "Repository")
                        .WithMany("TeamRoles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Domain.GitCandyTeam", "Team")
                        .WithMany("RepositoryRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyUserRepositoryRole", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyRepository", "Repository")
                        .WithMany("UserRoles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", "User")
                        .WithMany("RepositoryRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyUserTeamRole", b =>
                {
                    b.HasOne("GitCandy.Data.Domain.GitCandyTeam", "Team")
                        .WithMany("UserRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", "User")
                        .WithMany("TeamRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GitCandy.Data.Identity.GitCandyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyNamespace", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyRepository", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("TeamRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GitCandy.Data.Domain.GitCandyTeam", b =>
                {
                    b.Navigation("Namespace");

                    b.Navigation("RepositoryRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GitCandy.Data.Identity.GitCandyUser", b =>
                {
                    b.Navigation("Namespace");

                    b.Navigation("RepositoryRoles");

                    b.Navigation("SshKeys");

                    b.Navigation("TeamRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
